export { default as TemplateIcon } from './TemplateIcon'
export { default as BusquedaIcon } from './Busqueda'
export { default as PaperIcon } from './PaperIcon'
export { default as StarIcon } from './StarIcon'
export { default as WorkIcon } from './WorkIcon'
export { default as Spinner } from './Spinner'
export { default as SearchIcon } from './SearchIcon'
export { default as VerticalDotsIcon } from './VerticalDotsIcon '
export { default as TableDashboardIcon } from './TableDashboardIcon'
export { default as UserIcon } from './UserIcon'
export { default as ArrowDown } from './ArrowDown'
